### ISSUE TITLE
Chrome 54.0.2840.50 beta-m (64-bit) opens large images on its own viewer instead of Viewhance

### ISSUE THREAD

**Issue by Jadelor** [Deathamns/Viewhance#19]
So yeah. For some reason, the latest Chrome beta (Version 54.0.2840.50 beta-m (64-bit)) opens images that are higher-res than [some number] using its own viewer instead of Viewhance now. I can force them to open in Viewhance via Ctrl-Alt-click from a page, but left to its own, Chrome defaults to its own viewer. It's strange.

I disabled all the other extensions and cleared all experimental flags to rule out random glitches of my own accord.

If you need more info, please let me know.

**Comment by Jadelor** [comment]
Oh, realized this might be a duplicate of https://github.com/Deathamns/Viewhance/issues/18

**Comment by erasedff** [comment]
Similar issue here. Started happening since beta 53 (I think) and it's the same on the latest dev v55.0.2883.9
Not sure the ctrl-alt thing you referencing since ctrl-alt-clicking an image link doesn't fix the issue for me.
Here's an example of a "broken" image: http://i.imgur.com/CwJxyoZ.jpg
And here's a "working" image: http://i.imgur.com/el0gp37.jpg

**Comment by Deathamns** [comment]
Fixed in 8b481dd. If I will have time, I'll publish a new release for Chrome.
