### ISSUE TITLE
[Feature Request] SVG & Smoth Zooom

### ISSUE THREAD

**Issue by duarteframos** [Deathamns/Viewhance#25]
Probably one of the best image viewers in the webstore, really satisfied. I only have a few requests to be perfect:

1 - Support for also viewing SVG Vector Images - It already supports so many file formats, adding this one to the 'whitelist' would probably easy (no?)

2 - Smooth zooming - Non-stepped smooth zooming/panning like the [Image Viewer](https://chrome.google.com/webstore/detail/image-viewer/kcljlcpbfbkapegpifkodjdmdllgdlmk) extension

3 - Allow dragging to system/file manager - Dragging image outside browser window would save the image locally, although I understand this may collide with the current panning functionality(?)

4 - Tooltips for the toolbar buttons

**Comment by Deathamns** [comment]
1) It's not that simple. Supporting SVGs requires a different handling, since an SVG itself is a document. But my main reason to not support them is that they can have interactive elements (e.g., they can handle mouse events, or change their structure) where the extension would be an interference.
2) I investigate about this, but my current design probably won't make it easy.
3) Already possible. If the image fits into the view-port, then you can drag it from its right edge (30px), or before dragging hold Ctrl or Alt (which is always available).
4) Don't see the point. If you already know what the buttons do, tooltips seem unnecessary. Also, they would be the only things that would require translations on image documents (content scripts can't reach translation strings, they need to communicate with the background process, which also needs to be solved then).

**Comment by duarteframos** [comment]
1 - Ah had not though about those details with SVG, shame it's not that simple. would be very useful for most simple SVG files with no interaction.

3 - Cool I'll try it right now.

4 - Thing is I didn't know what the buttons did, icons are not always clear, had to click them to find out, hence my request. But no worries, with continued use I'm sure I'll get used to it.
On a side note, if you ever want to include tooltips I'll be glad to help translate, I can contribute Portuguese pt_PT strings if you like ;)

Anyway, thanks for the prompt response, all the best! :)

**Comment by Deathamns** [comment]
4. The extension had a website hosted on Google Drive, where I explained the buttons. Unfortunately Drive stopped supporting HTML hosting, and I didn't try to find a new host.

**Comment by Deathamns** [comment]
Unfortunately the first two request is not trivial, so most probably I won't deal with them.

Update on the last two:
3. Now it's possible to drag images that are fit the view-port without holding Ctrl (when panning is active, Ctrl is still needed).
4. New homepage: https://deathamns.github.io/Viewhance/ (shortlink: https://tiny.cc/Viewhance)

**Comment by duarteframos** [comment]
Hey this is cool, I'm sold. For the time being I'll replace my image viewer extension with this one, convenience of saving image to desktop by drag and drop beats smooth zooming.

Thanks for the answer and great support! :)

**Comment by duarteframos** [comment]
@Deathamns About my request #2 - Smooth Zooming as the Image Viewer extension.

It might not be so hard to implement. I've been playing around with customizing CSS in settings page and kind of figured out how to add it.

If you add something like `transition: 1s;` to `#media` the transition effect basically takes care of smoothing movement by itself.

Of course it sometimes glitches a bit, generally if you interrupt it mid animation, or move the mouse about, changing zoom center, but it 's a start.

Hope this helps

**Comment by Deathamns** [comment]
When the image is smaller than the view-port it's positioned with `top`, `left` CSS properties, when it's larger, then it's positioned with scrollbars (I use the scrollbars because panning is noticeable smoother compared to dragging). So, I would need to do two types of animation; for CSS top-left, and for the scrollbars (which cannot be done with transitions). And of course synchronize these two somehow, which is probably not trivial.
