### ISSUE TITLE
small bugs that need your consideration...

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#3]
1.it seems that when maxthon update your add-in to a new version, some customer settings are reseted. i am not sure about that but please take a good care on it

in the picture below:
2.icon missing
3.the symbol in the image information cannot display properly. if you want it to be a "x", just use the alphabet:'x' to replace it
![default](https://cloud.githubusercontent.com/assets/7941949/8249662/354974ca-169f-11e5-909e-246f5be5ff13.png)

**Comment by Deathamns** [comment]
Some settings were removed and backed to default in the latest version, which was intentional.

The issue with the icon has been fixed in 1cec14b (however I won't publish a new version because of this, since it's minor).

That symbol seems an encoding problem in Maxthon, you should report it to them.

**Comment by kliop00023** [comment]
i think Maxthon knew because of my report

**Comment by Deathamns** [comment]
Workaround in 5f9b661 for the broken symbol issue.
