### ISSUE TITLE
would you confirm this bug? 

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#51]
i think there is a bug in the browser causing some gif w/ sound cannot be properly loaded.
e.g. https://i.imgur.com/Slay0YY.gif
Would you help me to confirm and explain here so that i can repost it?

**Comment by kliop00023** [comment]
https://i.imgur.com/Slay0YY.gifv https://i.imgur.com/Slay0YY.mp4 are working tho...

**Comment by Deathamns** [comment]
There is no bug here, and this is not related to the extension.

> https://i.imgur.com/Slay0YY.gif
This is a still image (imgur uses it as placeholder), it is not animated. Just because it has the file extension `gif`, it doesn't mean that it is animated. GIF files (animated or not) don't support audio.

> https://i.imgur.com/Slay0YY.gifv
This is not an image format (the file extension doesn't mean anything here), it is simply a webpage, which embeds a video or an image.

> https://i.imgur.com/Slay0YY.mp4
This is a video file. It can have sound.
