### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Deathamns/Viewhance#59]
1 - Please add compatibility with Foxy Gestures Zoom Right Click + Scroll,

2 - feature, when scrollbar is visible scroll if cursor is over.

3 - feature to disable toolbar animation (or have some css?)

4 - for instance I have 15 tabs with images, but are pages, no direct images, add a feature an keyboard shortcut, to open the largest image of all tabs, if possible in original tabs, or if not possible closing the originals.

thanks

**Comment by Deathamns** [comment]
1. I can use zoom gestures with that extension without any problems.
2. 5af071b
3. You can use this CSS: `#menu, #menu li:hover > ul {transition: all .001s !important}`
4. I'm not sure about this one.

**Comment by mrochaaa** [comment]
1 - You can use right click + scroll o Foxy Gestures? With Zoom with scroll enabled or disabled in Viewhance, I can't zoom, image don't change size only the side menu.

4 - About this feature, is because, in older FF had "show-the-image" plugin, very good, but today have one called "Largest image" but is bad, this do not close original tabs, and need add an popup rule every time, unusable... This feature can be very useful for Viewhance, because many site have images in pages, then in this sites Viewhance is unusable, imagine you, need "View Image" for 30 tabs to use Viewhance Viewer?

2 and 3 - Thank you

**Comment by Deathamns** [comment]
1. Because that feature scales the web-page, not the image. See #63.
4. I'm not interested implementing this. There is an image opener shortcut (disabled by default) with right long-press, and I'm satisfied with that.
