### ISSUE TITLE
player controls for gif not working

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#9]
test link:https://media.giphy.com/media/n5FNMVNQ33TUY/giphy.gif

i think it works in the last version, not sure :<

**Comment by Deathamns** [comment]
What player controls? And what do you mean by not working?

**Comment by kliop00023** [comment]
@Deathamns player controls for gif  in it there's only one function is called like that and you named it...
![default](https://cloud.githubusercontent.com/assets/7941949/9757651/7a7e7562-5714-11e5-8fea-173bd6fefde2.png)
![default](https://cloud.githubusercontent.com/assets/7941949/9757697/a6e5ca92-5714-11e5-913f-7fbb29d92cbc.png)

**Comment by Deathamns** [comment]
There are player controls for audios and videos only. You're showing me a screenshot of the frame-extractor.
I tested in Maxthon 4.4.7.600 (I assume this is the browser you're using), and as you said it didn't work.
I updated to 4.4.7.1000 and that worked for me. So, it's probably a browser issue, because it works normally in other browsers.

**Comment by Deathamns** [comment]
It is a [browser bug](http://forum.maxthon.com/index.php/topic/13010-using-new-image-in-extension-creates-wrong-object/), but it can be worked around. Fixed in 5d65118.
